name = "astro-project"
main = "./functions/api.js"
compatibility_date = "2025-01-06"

[[kv_namespaces]]
binding = "HABIT_DATA"
id = "8bfd64c0837e4b9e8b3207d473f2dde7"

[site]
bucket = "./dist" # where astro's build output goes
